name: Cypress Tests
on: [push]
jobs:
 Cypress-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2

     - name: Run Cypress Test
       uses: cypress-io/github-action@v5
       with:
         build: npm i -D cypress
         command: npx cypress run
         browser: chrome
         working-directory: client
 Jest-Test:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
     - run: cd server
     - run: npm test